### ISSUE TITLE
There is no code published

### ISSUE THREAD

**Issue by chrisranderson** [QingyongHu/SpinNet#2]
I know this is obvious, but I'd like to have a place that I can subscribe to for changes.

**Comment by AurelienBrn** [comment]
Hello all, 

I am very interested in implementing your solution for UAV lidar point cloud registration. 
Any update on a release date for your code ? :)

**Comment by QingyongHu** [comment]
Hi @chrisranderson @AurelienBrn,
Thanks for your interest in our work!

Sorry for my late response, since I am busy with the ICCV submission during this period. 

We are going through the final inspection of the code, and it is expected to be released at the end of March :)

Best

**Comment by tangbohu** [comment]
I  am very interested in this work. I wonder when the codes will be made public.

**Comment by QingyongHu** [comment]
Hi @tangbohu @chrisranderson @AurelienBrn ，
Thanks for your patience, the code has finally released :)
Enjoy~
