### ISSUE TITLE
Pre-Trained Models

### ISSUE THREAD

**Issue by chpohl** [QingyongHu/SpinNet#22]
Hey, 

could you provide some pre-trained models that you used in your work? I want to test if I can use your network for my own work, but I don't have the possibility to train the network myself. Your help would be much appreciated.

**Comment by ramdrop** [comment]
Hi, 
Thank you for open sourcing your code. Could you please provide pre-trained models on the 3DMatch dataset, so that I can have a quick evaluation of SpinNet on other datasets?
