### ISSUE TITLE
How is the data generated

### ISSUE THREAD

**Issue by tangbohu** [QingyongHu/SpinNet#3]
Could you share the method to generate data, e.g., 3DMatch, such that I could generate by myself instead of downloading from google drive slowly? Beside, is it possible to share those data with Baidu Yun?

**Comment by tangbohu** [comment]
The downloading from google drive would be stoppted by the server frequently.

**Comment by QingyongHu** [comment]
Hi @tangbohu, Thanks for your interest in our work!

We are uploading the data to the Baidu Yun and preparing for the data preprocessing code, please stay tuned.

Best,

**Comment by tangbohu** [comment]
@QingyongHu Thanks very much for your kindness!

**Comment by QingyongHu** [comment]
@tangbohu 
Hi, the data has been uploaded to Baidu Yun.

Best,

**Comment by tangbohu** [comment]
Thanks!
