### ISSUE TITLE
How long is the training?

### ISSUE THREAD

**Issue by Alicebash** [QingyongHu/SpinNet#4]
Hello, could you please tell me according to the documents ' SpinNet/ThreeDMatch/Train/train. Py ' set the batch size = 79 for training, spend time is it?

**Comment by aosheng1996** [comment]
Hi @Alicebash, Thanks for your interest in our work!

It takes about 4 hours to train 1 epoch on the 3DMatch dataset.

Best,

**Comment by Alicebash** [comment]
What are your hardware requirements?How many cards did you use?

**Comment by aosheng1996** [comment]
We used 4 RTX2080Ti GPUs for training. If you are interested, you can try to adjust the hyperparameters to reduce GPU memory usage. By the way, we evaluated the performance of our SpinNet under varying parameters in the next version.

**Comment by pheepa** [comment]
> We used 4 RTX2080Ti GPUs for training. If you are interested, you can try to adjust the hyperparameters to reduce GPU memory usage. By the way, we evaluated the performance of our SpinNet under varying parameters in the next version.

I have RTX2070, can you help me choose the parameters of training.
which batch_size should I use?

**Comment by aosheng1996** [comment]
> > We used 4 RTX2080Ti GPUs for training. If you are interested, you can try to adjust the hyperparameters to reduce GPU memory usage. By the way, we evaluated the performance of our SpinNet under varying parameters in the next version.
> 
> I have RTX2070, can you help me choose the parameters of training.
> which batch_size should I use?

Hi, @pheepa,
You can try to adjust the hyperparameters J, K, L of the sphere voxelization to reduce GPU memory usage. For example, in `SpinNet/ThreeDMatch/Train/train.py` you can reduce rad_n, ele_n, azi_n to 7, 20, 40 respectively, and comment out the 79th line of code in `SpinNet/network/ThreeDCCN.py`. Then, you can adjust batch_size appropriately depending on the GPU memory usage.

**Comment by qsisi** [comment]
> We used 4 RTX2080Ti GPUs for training. If you are interested, you can try to adjust the hyperparameters to reduce GPU memory usage. By the way, we evaluated the performance of our SpinNet under varying parameters in the next version.

Hello! 

As far as I can see, the current released version doesn't support Multi-GPU implementation, the hyper-params are set clearly for Multi-GPU (train_batch_size is set to 76, I manage to run the code in my single TITAN V with 11 GB memory by setting it from 76 -> 16) , so could you release the Multi-GPU implementation version?

Best.
