### ISSUE TITLE
meta-data Fig. 4

### ISSUE THREAD

**Issue by fabiopoiesi** [QingyongHu/SpinNet#8]
Hi,

Would it be possible to have the meta-data of Fig. 4 to use it to add new results to it?

Thanks

**Comment by aosheng1996** [comment]
Hi, @fabiopoiesi, thanks for your interest in our work!

The meta-data of Fig. 4 is here.
[Inlier_threshold.txt](https://github.com/QingyongHu/SpinNet/files/6356489/Inlier_threshold.txt)
[Distance_threshold.txt](https://github.com/QingyongHu/SpinNet/files/6356490/Distance_threshold.txt)

best,
Sheng

**Comment by fabiopoiesi** [comment]
Thanks!
